version: "3"
services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command:
      - --account="0x1E64432C47c1F902B8B624F85122B6b4437bef9E,1000000000000000000000" # Account with 1000 ETH
      - --blockTime=1
    environment:
      - HARD_CODED_TX="Sample Transaction Data"
